AssemblyException: Make the error indicator show correctly for multiline source.
Prints the text on a new line so that multiple lines stay aligned, this probably
is easier to read even for single line errors. Column indicator is adjusted so
that it just takes the last line.